### ISSUE TITLE
Changing highlight color for favicon and apple-touch-icon

### ISSUE THREAD

**Issue by mroach** [Vimux/Mainroad#219] opened 2020-07-09 16:09 UTC
Hello! I love this theme and found it to be the perfect fit for my site.
I wanted to get the `favicon.ico` and `apple-touch-icon.png` to match my `hightlightColor`. I created a `Makefile` to generate both. I wanted to pass this along for your consideration to include in the repo or documentation.

https://github.com/mroach/mroach.com/blob/master/Makefile

**Comment by Vimux** [comment] 2020-07-17 19:53
It is a really useful addition, but it doesn't suit some of my requirements because it's not cross-platform. Any (non-dev related) things inside the repo should be work for all major platforms (Windows, macOS, Linux) without additional hassle for users.

I do not plan to close this issue right now, maybe someone else will suggest some ideas/alternative options.

**Comment by mroach** [comment] 2020-07-17 21:16
What would the requirements be for cross platform? For example, this could be run via Docker but then that would require users to have Docker installed. Another option might be to just unroll this as a series of commands that could be pasted into documentation and users can run if they're interested to. Example:

```shell
convert -size 16x16 xc:black -fill "rgb(58,110,165)" -draw "rectangle 0,12, 16,16" favicon-16.ico
convert -size 32x32 xc:black -fill "rgb(58,110,165)" -draw "rectangle 0,24, 32,32" favicon-32.ico
convert -size 48x48 xc:black -fill "rgb(58,110,165)" -draw "rectangle 0,36, 48,48" favicon-48.ico
convert -size 64x64 xc:black -fill "rgb(58,110,165)" -draw "rectangle 0,48, 64,64" favicon-64.ico
convert favicon-16.ico favicon-32.ico favicon-48.ico favicon-64.ico static/favicon.ico
rm favicon-{16,32,48,64}.ico

convert -size 180x180 xc:black -fill "rgb(58,110,165)" -draw "rectangle 0,135, 180,180" static/apple-touch-icon.png
```

**Comment by Vimux** [comment] 2020-07-18 18:00
> Another option might be to just unroll this as a series of commands that could be pasted into documentation and users can run if they're interested to.

Same here. Many of our users will see it something like this:

```
command `convert` not found
```

`convert` is part of the ImageMagick package which is not installed by default.

**Comment by Vimux** [comment] 2022-01-21 17:56
Long time no see.

> Another option might be to just unroll this as a series of commands that could be pasted into documentation and users can run if they're interested to.

Agree. I thought about something like that:

```sh
a=#E22D30;a=\\x${a:5:2}\\x${a:3:2}\\x${a:1:2};for i in 98 274 578;do printf $a|dd of=static/favicon.ico bs=1 seek=$i conv=notrunc;done
```

I tested on Alpine Linux. Windows 10 (with WSL or MINGW) should work, but I don't have a chance to check it. My macOS machine contains so many additional packages that I can't say for sure that this should work out of the box. Anyway, the problem is PNG. PNG needs CRC, so our second one-liner would be a very long-liner, I guess.

---

After all, I'm thinking of putting script sources somewhere in the documentation.

**Comment by Vimux** [comment] 2022-01-24 16:40
After a bit of size optimization, here is one-liner for our `apple-touch-icon.png`:

```sh
a=#E22D30;a=$(echo 504C54452A2A2A${a:1:6}|sed -e 's/../\\x&/g');printf $a|gzip|tail -c8|od -tx4 -N4 -An|xargs|sed -e 's/../\\x&/g'|printf $a$(cat -)|dd of=static/apple-touch-icon.png bs=1 seek=37 conv=notrunc
```

It is a big, still acceptable one-liner for our use-case, I guess.

**Closed** 2022-01-24 19:04 UTC
Labels: enhancement
