### ISSUE TITLE
Respect content post formatting in preview

### ISSUE THREAD

**Issue by atzawada** [Vimux/Mainroad#336] opened 2023-08-10 01:55 UTC
In the content preview section, it would be nice if Mainroad could respect at least part of the formatting that the post being previewed has. Especially without line breaks, posts with certain formatting can look a little silly. With some poking around and a push in the right direction I can probably contribute this, if there is interest.

**Comment by Vimux** [comment] 2023-08-10 13:05
Duplicate of https://github.com/Vimux/Mainroad/issues/130? Or am I missing something?

**Comment by Vimux** [comment] 2023-08-18 17:31
@atzawada, ping.

Can you please confirm that this issue is a duplicate? If not, please provide more details (example).

**Comment by Vimux** [comment] 2023-09-29 12:05
[Summary splitting options | Hugo Documentation ](https://gohugo.io/content-management/summaries/#summary-splitting-options)

Closed.

**Closed by Vimux** 2023-09-29 12:05 UTC
Labels: duplicate
